### PR TITLE
 added viz for gasflow,waterflow,weight,humidity,thermostat,leaf,radiation

### PR DESCRIPTION
**Pull request by xztraz**
image
image
image
image
image
image
image

I think that should be all!

### CODE REVIEW

**Comment by xztraz** [comment]
Some sensors month viz don't work for since they have other parameters for month. v_avg for example.   disable month button or also look for [datatype]_avg for those maybe?

**Comment by xztraz** [comment]
should solve https://github.com/flatsiedatsie/domoticz-aurora-theme/issues/14 if i haven't missed something

**Comment by flatsiedatsie** [comment]
disable month button would probably be easiest, as it's now possible to target the item specifically with css.

Which sensors should have their month hidden?

it's then possible to add some CSS to hide the button in _dashboard_show_data_visualizations.css_

Something like:

.leaf .datavizbtn{
display:none!important
}

**Comment by xztraz** [comment]
i'll make a list.

**Pull request merged**
